version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    command: "--bind_ip_all --replSet rs0"
    healthcheck:
      test: test $$(echo "rs.status().ok || rs.initiate().ok" | mongo --quiet) -eq 1
      start_period: 5s
      interval: 10s
